//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RoomBooking
    {
        public int Id { get; set; }
        public int RoomId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int UserId { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual tbl_Room tbl_Room { get; set; }
    }
}
